lightgbm:
  classpath: aequitas.flow.methods.base_estimator.lightgbm.LightGBM
  args:
    boosting_type:
      - dart
      - gbdt

    enable_bundle:
      - False

    n_estimators:
      type: int
      range: [10, 100]

    min_child_samples:
      type: int
      range: [1, 500]
      log: True

    learning_rate:
      type: float
      range: [0.001, 0.1]

    random_state:
      - 42

    n_jobs:
      - 40