Massaging:
  classpath: aequitas.flow.methods.preprocessing.massaging.Massaging
  args:
    classifier:
      - sklearn.naive_bayes.GaussianNB
      - lightgbm.LGBMClassifier

    boosting_type:
      - dart
      - gbdt

    random_state:
      - 42

    n_jobs:
      - 40