Feature Importance Suppression:
  classpath: aequitas.flow.methods.preprocessing.feature_importance_suppression.FeatureImportanceSuppression
  args:
    auc_threshold:
      type: float
      range: [0.1, 0.9]

    feature_importance_threshold:
      type: float
      range: [0.05, 0.5]

    n_estimators:
      type: int
      range: [10, 100]

    seed:
      - 42

    n_jobs:
      - 40