baf_typeii_label_1_0_20:
  args:
    dataset: BankAccountFraud
    noise_rates:
      0: 0.0
      1: 0.2
    variant: TypeII
    y_dependant:
    - 1
  classpath: datasets.NoisyDataset
  threshold:
    threshold_type: top_pct
    threshold_value: 0.01
